In [32]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sea
import torch

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

In [33]:
df = pd.read_csv('Dataset-Mental-Disorders.csv')
df

,Patient Number,Sadness,Euphoric,Exhausted,Sleep dissorder,Mood Swing,Suicidal thoughts,Anorxia,Authority Respect,Try-Explanation,Aggressive Response,Ignore & Move-On,Nervous Break-down,Admit Mistakes,Overthinking,Sexual Activity,Concentration,Optimisim,Expert Diagnose
0,Patiant-01,Usually,Seldom,Sometimes,Sometimes,YES,YES,NO,NO,YES,NO,NO,YES,YES,YES,3 From 10,3 From 10,4 From 10,Bipolar Type-2
1,Patiant-02,Usually,Seldom,Usually,Sometimes,NO,YES,NO,NO,NO,NO,NO,NO,NO,NO,4 From 10,2 From 10,5 From 10,Depression
2,Patiant-03,Sometimes,Most-Often,Sometimes,Sometimes,YES,NO,NO,NO,YES,YES,NO,YES,YES,NO,6 From 10,5 From 10,7 From 10,Bipolar Type-1
3,Patiant-04,Usually,Seldom,Usually,Most-Often,YES,YES,YES,NO,YES,NO,NO,NO,NO,NO,3 From 10,2 From 10,2 From 10,Bipolar Type-2
4,Patiant-05,Usually,Usually,Sometimes,Sometimes,NO,NO,NO,NO,NO,NO,NO,YES,YES,YES,5 From 10,5 From 10,6 From 10,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Patiant-116,Most-Often,Seldom,Usually,Sometimes,NO,YES,NO,NO,YES,NO,YES,NO,NO,YES,2 From 10,5 From 10,3 From 10,Depression
116,Patiant-117,Sometimes,Sometimes,Sometimes,Seldom,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,6 From 10,7 From 10,8 From 10,Bipolar Type-1
117,Patiant-118,Usually,Sometimes,Usually,Sometimes,YES,NO,YES,YES,NO,NO,NO,YES,NO,YES,1 From 10,5 From 10,3 From 10,Bipolar Type-2
118,Patiant-119,Usually,Sometimes,Seldom,Seldom,NO,YES,YES,NO,YES,YES,YES,NO,YES,YES,7 From 10,7 From 10,7 From 10,Depression
119,Patiant-120,Sometimes,Usually,Seldom,Usually,NO,NO,NO,YES,YES,NO,YES,YES,NO,NO,7 From 10,3 From 10,8 From 10,Normal

In [34]:
# Manipulating the data we'll need
df = df.drop(['Patient Number'], axis=1) # -> droping ID
df.head()

,Sadness,Euphoric,Exhausted,Sleep dissorder,Mood Swing,Suicidal thoughts,Anorxia,Authority Respect,Try-Explanation,Aggressive Response,Ignore & Move-On,Nervous Break-down,Admit Mistakes,Overthinking,Sexual Activity,Concentration,Optimisim,Expert Diagnose
0,Usually,Seldom,Sometimes,Sometimes,YES,YES,NO,NO,YES,NO,NO,YES,YES,YES,3 From 10,3 From 10,4 From 10,Bipolar Type-2
1,Usually,Seldom,Usually,Sometimes,NO,YES,NO,NO,NO,NO,NO,NO,NO,NO,4 From 10,2 From 10,5 From 10,Depression
2,Sometimes,Most-Often,Sometimes,Sometimes,YES,NO,NO,NO,YES,YES,NO,YES,YES,NO,6 From 10,5 From 10,7 From 10,Bipolar Type-1
3,Usually,Seldom,Usually,Most-Often,YES,YES,YES,NO,YES,NO,NO,NO,NO,NO,3 From 10,2 From 10,2 From 10,Bipolar Type-2
4,Usually,Usually,Sometimes,Sometimes,NO,NO,NO,NO,NO,NO,NO,YES,YES,YES,5 From 10,5 From 10,6 From 10,Normal

In [35]:
y = df.iloc[:, 4:14] # Searching for only bolean values
y.head()

,Mood Swing,Suicidal thoughts,Anorxia,Authority Respect,Try-Explanation,Aggressive Response,Ignore & Move-On,Nervous Break-down,Admit Mistakes,Overthinking
0,YES,YES,NO,NO,YES,NO,NO,YES,YES,YES
1,NO,YES,NO,NO,NO,NO,NO,NO,NO,NO
2,YES,NO,NO,NO,YES,YES,NO,YES,YES,NO
3,YES,YES,YES,NO,YES,NO,NO,NO,NO,NO
4,NO,NO,NO,NO,NO,NO,NO,YES,YES,YES

In [36]:
df.head() # See, the colluns 4:13

,Sadness,Euphoric,Exhausted,Sleep dissorder,Mood Swing,Suicidal thoughts,Anorxia,Authority Respect,Try-Explanation,Aggressive Response,Ignore & Move-On,Nervous Break-down,Admit Mistakes,Overthinking,Sexual Activity,Concentration,Optimisim,Expert Diagnose
0,Usually,Seldom,Sometimes,Sometimes,YES,YES,NO,NO,YES,NO,NO,YES,YES,YES,3 From 10,3 From 10,4 From 10,Bipolar Type-2
1,Usually,Seldom,Usually,Sometimes,NO,YES,NO,NO,NO,NO,NO,NO,NO,NO,4 From 10,2 From 10,5 From 10,Depression
2,Sometimes,Most-Often,Sometimes,Sometimes,YES,NO,NO,NO,YES,YES,NO,YES,YES,NO,6 From 10,5 From 10,7 From 10,Bipolar Type-1
3,Usually,Seldom,Usually,Most-Often,YES,YES,YES,NO,YES,NO,NO,NO,NO,NO,3 From 10,2 From 10,2 From 10,Bipolar Type-2
4,Usually,Usually,Sometimes,Sometimes,NO,NO,NO,NO,NO,NO,NO,YES,YES,YES,5 From 10,5 From 10,6 From 10,Normal

In [37]:
string_df = df.iloc[:, 14:17]
string_df.head()
# Strings to manipulate

  Sexual Activity Concentration  Optimisim
0       3 From 10     3 From 10  4 From 10
1       4 From 10     2 From 10  5 From 10
2       6 From 10     5 From 10  7 From 10
3       3 From 10     2 From 10  2 From 10
4       5 From 10     5 From 10  6 From 10

In [38]:
y = pd.DataFrame(df.iloc[:,-1])

y["Expert Diagnose"].unique() # array(['Bipolar Type-2', 'Depression', 'Bipolar Type-1', 'Normal']

y = pd.get_dummies(y,prefix=['Expert Diagnose'],
                   columns=['Expert Diagnose'],
                   drop_first=False)

In [39]:
df['Sexual Activity'] = df['Sexual Activity'].str.split().str[0]
df['Concentration'] = df['Concentration'].str.split().str[0]
df['Optimisim'] = df['Optimisim'].str.split().str[0]
df.head()

for x in df['Sexual Activity']:
    x = int(x)

for x in df['Concentration']:
    x = int(x)

for x in df['Optimisim']:
    x = int(x)

In [40]:
df = df.drop(['Expert Diagnose'], axis=1)
df = df.join(y, how='outer')

need_encode = df.iloc[:, 0:14]
need_encode = need_encode.apply(LabelEncoder().fit_transform)

In [41]:
need_encode.iloc[:, 4:] = need_encode.iloc[:, 4:].astype(bool)

In [42]:
need_encode

,Sadness,Euphoric,Exhausted,Sleep dissorder,Mood Swing,Suicidal thoughts,Anorxia,Authority Respect,Try-Explanation,Aggressive Response,Ignore & Move-On,Nervous Break-down,Admit Mistakes,Overthinking
0,3,1,2,2,True,True,False,False,True,False,False,True,True,True
1,3,1,3,2,False,True,False,False,False,False,False,False,False,False
2,2,0,2,2,True,False,False,False,True,True,False,True,True,False
3,3,1,3,0,True,True,True,False,True,False,False,False,False,False
4,3,3,2,2,False,False,False,False,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,0,1,3,2,False,True,False,False,True,False,True,False,False,True
116,2,2,2,1,True,False,False,False,False,True,False,False,False,True
117,3,2,3,2,True,False,True,True,False,False,False,True,False,True
118,3,2,1,1,False,True,True,False,True,True,True,False,True,True
119,2,3,1,3,False,False,False,True,True,False,True,True,False,False

In [44]:
df.iloc[:,0:14] = need_encode
df.to_csv('dataset-mental-disorders-normalized', sep=',', index=False, encoding='utf-8')